apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Maxim un pod peste numărul dorit
      maxUnavailable: 0  # Niciun pod indisponibil în timpul actualizării
  template:
    metadata:
      labels:
        app: ac-app
    spec:
      containers:
      - name: ac-app-container
        image: ac-app:latest  # Schimbăm înapoi la imaginea existentă
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   failureThreshold: 3